# Generated by Django 6.0.7 on 2026-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0003_alter_propertyimage_options_propertyimage_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(help_text='Short teaser shown on the Journal list page.', max_length=300)),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(upload_to='journal/covers/')),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_properties', models.ManyToManyField(blank=True, help_text='Optional — link this post to specific properties (e.g. a property spotlight).', related_name='journal_posts', to='portfolio.property')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
