# Generated by Django 6.0.7 on 2026-07-20 20:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('portfolio', '0003_alter_propertyimage_options_propertyimage_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalpost',
            options={'ordering': ['-published_at'], 'verbose_name': 'Journal post', 'verbose_name_plural': 'Journal posts'},
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='related_properties',
            field=models.ManyToManyField(blank=True, help_text='Optional — link this post to one or more related properties.', related_name='journal_posts', to='portfolio.property'),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title.', unique=True),
        ),
    ]
