# Generated by Django 6.0.7 on 2026-08-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('enquiry_type', models.CharField(choices=[('general', 'General enquiry'), ('management', 'Property management services'), ('rental', 'Holiday rental enquiry'), ('restoration', 'Restoration management'), ('post_purchase', 'Post-purchase support'), ('other', 'Something else')], default='general', max_length=30)),
                ('property_name', models.CharField(blank=True, help_text='Privacy-safe property title supplied through a property enquiry.', max_length=150)),
                ('message', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('replied', 'Replied'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', editable=False, max_length=20)),
                ('email_error', models.CharField(blank=True, editable=False, help_text='Internal delivery information. Never display this publicly.', max_length=500)),
                ('internal_notes', models.TextField(blank=True, help_text='Private notes visible only to authorised Oliverde staff.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'contact enquiry',
                'verbose_name_plural': 'contact enquiries',
                'ordering': ('-submitted_at',),
            },
        ),
    ]
