# Generated by Django 6.0.7 on 2026-08-04 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('portfolio', '0006_alter_property_land_size_hectares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiry',
            name='property_name',
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='property',
            field=models.ForeignKey(blank=True, help_text='The related Oliverde property, when the enquiry originated from a property page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_enquiries', to='portfolio.property'),
        ),
    ]
