# Generated by Django 6.0.7 on 2026-07-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Property Manager'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
