# Generated by Django 6.0.7 on 2026-07-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_servicefeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['section', 'order', 'pk']},
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='section',
            field=models.CharField(choices=[('arrival', 'Arrival'), ('exterior', 'Exterior'), ('living', 'Living Spaces'), ('bedrooms', 'Bedrooms'), ('outdoors', 'Outdoor Living'), ('gardens', 'Gardens & Grounds'), ('details', 'Architectural Details'), ('views', 'Views')], default='exterior', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
