# Generated by Django 6.0.7 on 2026-07-31 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_propertyimage_options_propertyimage_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('comfort', 'Comfort'), ('outdoor', 'Outdoor Living'), ('practical', 'Practical'), ('services', 'Optional Services')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Property amenities',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-featured', 'featured_order', 'title'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='servicefeature',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AddField(
            model_name='property',
            name='air_conditioning',
            field=models.CharField(choices=[('none', 'No Air Conditioning'), ('partial', 'Air Conditioning in Selected Rooms'), ('bedrooms', 'Air Conditioning in Bedrooms'), ('throughout', 'Air Conditioning Throughout')], default='none', help_text='Select the general air-conditioning arrangement. Use the details field for room-specific information.', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='air_conditioning_details',
            field=models.CharField(blank=True, help_text="Optional room-specific information, for example: 'Air conditioning in all bedrooms and the main living room.'", max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='available_for_rental',
            field=models.BooleanField(default=False, help_text='Enable when this managed property is also available for private rental.'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Controls the order of featured properties. Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='property',
            name='pool',
            field=models.CharField(choices=[('none', 'No Swimming Pool'), ('private', 'Private Swimming Pool'), ('shared', 'Shared Swimming Pool')], default='none', help_text="Select the property's swimming-pool arrangement.", max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='pool_details',
            field=models.CharField(blank=True, help_text="Optional pool information, for example: 'Private infinity pool open from May to October.'", max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='pool_heated',
            field=models.BooleanField(default=False, help_text='Enable only when the swimming pool can be heated.'),
        ),
        migrations.AddField(
            model_name='property',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Random public identifier used in the property URL. This prevents the internal property name from appearing in or being inferred from the URL.', unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='public_title',
            field=models.CharField(blank=True, help_text="Privacy-safe public name, for example 'The Cypress Estate' or 'Olive Grove House'.", max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_banner_text',
            field=models.CharField(blank=True, default='Available for Private Rental', help_text='Banner displayed on rental properties. Leave blank to use the default wording.', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_intro',
            field=models.TextField(blank=True, help_text='Optional introduction displayed near the rental enquiry area.'),
        ),
        migrations.AddField(
            model_name='property',
            name='show_property_highlights',
            field=models.BooleanField(default=False, help_text='Display air-conditioning, pool and selected amenity information on the public property page. Optional for managed-only homes and recommended for rental properties.'),
        ),
        migrations.AddField(
            model_name='property',
            name='show_real_name_publicly',
            field=models.BooleanField(default=False, help_text="Enable only when the owner has approved public use of the property's real name."),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Use a privacy-safe description. Do not include the real property name unless approved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(help_text="Privacy-safe editorial slug. Never use the property's real internal name unless publication has been approved.", unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(help_text='Internal property name used by the Oliverde team. It remains private unless public use is approved.', max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(help_text='Use an approved public name, initials or anonymous label where discretion is required.', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Optional public highlights such as Outdoor Dining, Pizza Oven, Landscaped Gardens or Pet Friendly. Recommended for rental properties.', related_name='properties', to='portfolio.propertyamenity'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='A short description of the image for accessibility and search engines.', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.service')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
