# Generated by Django 6.0.7 on 2026-07-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_propertyamenity_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ('order', 'pk'), 'verbose_name': 'service image', 'verbose_name_plural': 'service images'},
        ),
    ]
