# Generated by Django 6.0.7 on 2026-07-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_serviceimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='land_size_hectares',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
